# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813cb9214aad17c2a587a465fa43c0da444df9da33d7489b9259f203290dbbb8b039e94b46fa4d913a704c78e4a34cde0641ed28fa7c4c6081269e551178accd

test:
  secret_key_base: d54fa8ae3c4f6ad2da582403045480bb73bc34547053b2deb4b53b7248db6185d6441f1bb2882f0990b6d7fb25b622472139f68eec177b7c0d60e01c39ba1569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
